

test_that("compilation works", {

  code <- "
#include <R.h>
#include <Rdefines.h>

SEXP add(SEXP val1, SEXP val2) {
  return ScalarReal(asReal(val1) + asReal(val2));
}
"
  
  # Keep reference to returned object.
  # C library will be unloaded when 'dll' variable is garbage collected.
  dll <- callme(code)
  
  # Manual call
  expect_equal(.Call("add", 1, 2.5), 3.5)
  
  # Wrapper function automatically generated by 'callme()'
  expect_equal(dll$add(99.5, 0.5), 100)
  
})
