

test_that("compilation works", {

  code <- "
#include <R.h>
#include <Rdefines.h>

SEXP add_(SEXP val1_, SEXP val2_) {
  return ScalarReal(asReal(val1_) + asReal(val2_));
}
"
  
  # Keep reference to returned object.
  # C library will be unloaded when 'dll' variable is garbage collected.
  dll <- callme(code)
  
  # Manual call
  expect_equal(.Call("add_", 1, 2.5), 3.5)
  
  # Wrapper function automatically generated by 'callme()'
  expect_equal(dll$add_(99.5, 0.5), 100)
  
})
